# Generated by Django 5.0.4 on 2026-05-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_sms_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='icon',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo_url',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='doctors/'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='icon_url',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='specialists/'),
        ),
    ]
