# Generated by Django 5.0.4 on 2026-05-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_review_booking_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChipWinning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('chip_type', models.CharField(max_length=100, verbose_name='Какая фишка')),
                ('kaloev_id', models.CharField(max_length=100, verbose_name='ID Kaloev')),
            ],
            options={
                'verbose_name': 'Выигрыш фишки',
                'verbose_name_plural': 'Выигрыши фишек',
                'ordering': ['-created_at'],
            },
        ),
    ]
