# Generated by Django 5.0.4 on 2026-05-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0009_chipwinning"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChipWinning",
        ),
    ]