# Generated by Django 5.0.4 on 2026-05-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_paylink_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfeaturesettings',
            name='branches_enabled',
            field=models.BooleanField(default=True, help_text='Глобальный переключатель. Если выключить — во всём проекте скрываем работу с филиалами.', verbose_name='Филиалы (адреса) включены'),
        ),
        migrations.AlterField(
            model_name='projectfeaturesettings',
            name='paylink_enabled',
            field=models.BooleanField(default=True, help_text='Глобальный переключатель. Если выключить — Paylink/оплата отключены для всех. Дополнительно можно отключать Paylink на уровне организации и конкретного специалиста.', verbose_name='Paylink/оплата включены (глобально)'),
        ),
    ]
