# Generated by Django 5.0.4 on 2026-05-19 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_alter_projectfeaturesettings_branches_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='purpose',
            field=models.CharField(choices=[('register', 'register'), ('reset', 'reset'), ('login', 'login'), ('pro_login', 'pro_login')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProfessionalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='organizations.doctor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аккаунт специалиста',
                'verbose_name_plural': 'Аккаунты специалистов',
            },
        ),
    ]
