# Generated by Django 5.0.4 on 2026-05-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_remove_doctor_branch_doctor_branches_patient_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleexception',
            name='break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleexception',
            name='break_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleexception',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleexception',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
