# Generated by Django 5.0.4 on 2026-05-19 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_scheduleexception_break_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorspecialty',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.specialist', verbose_name='Специализация'),
        ),
    ]
