# Generated by Django 5.0.4 on 2026-05-22 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0025_rename_doctor_patient_to_professional_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingclientprofile',
            options={'verbose_name': 'Токен завершения профиля клиента', 'verbose_name_plural': 'Токены завершения профиля клиента'},
        ),
        migrations.AlterModelOptions(
            name='specialist',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        # NOTE: production DBs could have different index names because the project
        # lived under app_label='clinic' for a long time, and some deployments also
        # renamed DB objects. We therefore make index changes idempotent.
        migrations.RunSQL(
            sql="""
            DROP INDEX IF EXISTS clinic_book_doctor__105f78_idx;
            DROP INDEX IF EXISTS organizations_book_doctor__105f78_idx;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
              IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'clinic_pend_token_aef7d8_idx') THEN
                EXECUTE 'ALTER INDEX clinic_pend_token_aef7d8_idx RENAME TO clinic_pend_token_bc6b7f_idx';
              ELSIF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'organizations_pend_token_aef7d8_idx') THEN
                EXECUTE 'ALTER INDEX organizations_pend_token_aef7d8_idx RENAME TO clinic_pend_token_bc6b7f_idx';
              END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/photos/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professional',
            name='paylink_enabled',
            field=models.BooleanField(default=True, help_text='Если выключить — у этого врача будет скрыта/запрещена оплата (Paylink), даже если у организации и глобально включено.', verbose_name='Paylink/оплата включены'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='professionals/'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='primary_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_professionals', to='organizations.specialist'),
        ),
        migrations.AlterField(
            model_name='professionalspecialty',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_specialties', to='organizations.professional'),
        ),
        migrations.AlterField(
            model_name='professionalspecialty',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_specialties', to='organizations.specialist', verbose_name='Специальность'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['professional', 'booking_date', 'booking_time'], name='clinic_book_profess_46d6a5_idx'),
        ),
    ]
