# Generated by Django 5.0.4 on 2026-05-27 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0026_alter_pendingclientprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('paylink_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('failed', 'failed'), ('expired', 'expired')], default='pending', max_length=20)),
                ('provider_payload', models.JSONField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Оплата (Paylink)',
                'verbose_name_plural': 'Оплаты (Paylink)',
                'ordering': ['-created_at', '-id'],
            },
        ),
        # These indexes existed in earlier DB history. In new environments they may not exist.
        # - database_operations uses IF EXISTS for idempotency
        # - state_operations updates Django migration state so future makemigrations won't re-generate these changes
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS clinic_book_doctor__105f78_idx;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="ALTER INDEX IF EXISTS clinic_book_profess_46d6a5_idx RENAME TO organizatio_profess_8334e7_idx;",
                    reverse_sql="ALTER INDEX IF EXISTS organizatio_profess_8334e7_idx RENAME TO clinic_book_profess_46d6a5_idx;",
                ),
                migrations.RunSQL(
                    sql="ALTER INDEX IF EXISTS clinic_otpc_phone_9fde4c_idx RENAME TO organizatio_phone_9d90c9_idx;",
                    reverse_sql="ALTER INDEX IF EXISTS organizatio_phone_9d90c9_idx RENAME TO clinic_otpc_phone_9fde4c_idx;",
                ),
                migrations.RunSQL(
                    sql="ALTER INDEX IF EXISTS clinic_pend_token_aef7d8_idx RENAME TO organizatio_token_361183_idx;",
                    reverse_sql="ALTER INDEX IF EXISTS organizatio_token_361183_idx RENAME TO clinic_pend_token_aef7d8_idx;",
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='booking',
                    name='clinic_book_doctor__105f78_idx',
                ),
                migrations.RenameIndex(
                    model_name='booking',
                    new_name='organizatio_profess_8334e7_idx',
                    old_name='clinic_book_profess_46d6a5_idx',
                ),
                migrations.RenameIndex(
                    model_name='otpcode',
                    new_name='organizatio_phone_9d90c9_idx',
                    old_name='clinic_otpc_phone_9fde4c_idx',
                ),
                migrations.RenameIndex(
                    model_name='pendingclientprofile',
                    new_name='organizatio_token_361183_idx',
                    old_name='clinic_pend_token_aef7d8_idx',
                ),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='paylink_amount',
            field=models.IntegerField(default=0, help_text='Сколько сом нужно оплатить для брони в этом филиале.', verbose_name='Сумма брони (KGS)'),
        ),
        migrations.AddField(
            model_name='branch',
            name='paylink_enabled',
            field=models.BooleanField(default=False, help_text='Если включено — перед созданием записи требуется оплата брони. Если выключено — запись создаётся без оплаты.', verbose_name='Оплата/бронь через Paylink включена'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Клиент (если авторизован). Может быть null, если платёж инициирован до создания клиента.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='organizations.client'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_intent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='organizations.paymentintent'),
        ),
    ]
