# Generated by Django 5.0.4 on 2026-05-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0027_paymentintent_and_more'),
    ]

    operations = [
        # Legacy index renames (safe for new DBs where these indexes might not exist)
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS clinic_book_doctor__105f78_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS clinic_book_profess_46d6a5_idx RENAME TO organizatio_profess_8334e7_idx;",
            reverse_sql="ALTER INDEX IF EXISTS organizatio_profess_8334e7_idx RENAME TO clinic_book_profess_46d6a5_idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS clinic_otpc_phone_9fde4c_idx RENAME TO organizatio_phone_9d90c9_idx;",
            reverse_sql="ALTER INDEX IF EXISTS organizatio_phone_9d90c9_idx RENAME TO clinic_otpc_phone_9fde4c_idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS clinic_pend_token_aef7d8_idx RENAME TO organizatio_token_361183_idx;",
            reverse_sql="ALTER INDEX IF EXISTS organizatio_token_361183_idx RENAME TO clinic_pend_token_aef7d8_idx;",
        ),
    ]
