# Generated by Django 5.0.4 on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0028_remove_booking_clinic_book_doctor__105f78_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="paylink_token",
            field=models.TextField(
                blank=True,
                default="",
                help_text=(
                    "Bearer token для Bakai PayLink именно для этого филиала. "
                    "Если пусто — будет использован глобальный BAKAI_PAYLINK_TOKEN из .env"
                ),
                verbose_name="Paylink токен филиала",
            ),
        ),
    ]
