# Generated by Django 5.0.4 on 2026-06-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0029_branch_paylink_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPaylinkSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Настройки PayLink филиала',
                'verbose_name_plural': 'Настройки PayLink по филиалам',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('organizations.branch',),
        ),
        migrations.AddField(
            model_name='branch',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
    ]
