# Generated by Django 5.0.4 on 2026-06-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0031_backfill_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='api_key',
            field=models.CharField(blank=True, help_text='Используется для интеграции (например, GET /partner/bookings/)', max_length=255, null=True, unique=True, verbose_name='API-ключ'),
        ),
    ]
