# Generated by Django 5.0.4 on 2026-05-17 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='clinic_book_doctor__105f78_idx',
            old_name='clinic_book_doctor__e1b8b8_idx',
        ),
        migrations.RenameIndex(
            model_name='otpcode',
            new_name='clinic_otpc_phone_9fde4c_idx',
            old_name='clinic_otp_phone_0b5f2c_idx',
        ),
    ]
