# Generated by Django 5.0.4 on 2026-05-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_remove_doctor_photo_remove_specialist_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='icon_url',
            field=models.ImageField(blank=True, null=True, upload_to='specialists/'),
        ),
    ]
